#!/usr/bin/env python3
"""Regenerate the pin-map table in docs/HARDWARE.md from smart_stick/config.h.

The pin map is the one piece of hardware documentation that can be derived
rather than asserted, so it is derived. A hand-maintained copy drifts from
the firmware the first time somebody moves a wire.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG = os.path.join(ROOT, "smart_stick", "config.h")
DOC = os.path.join(ROOT, "docs", "HARDWARE.md")

STRAPPING = {"0", "2", "12", "15"}
INPUT_ONLY = {"34", "35", "36", "39"}

START = "<!-- PINMAP:BEGIN (generated by tools/gen_pinmap.py — do not edit by hand) -->"
END = "<!-- PINMAP:END -->"


def build_table(source: str) -> str:
    pins = re.findall(r"#define\s+(\w*_PIN)\s+(\d+)", source)
    seen = {}
    rows = []
    for name, num in pins:
        notes = []
        if num in INPUT_ONLY:
            notes.append("input-only")
        if num in STRAPPING:
            notes.append("strapping pin")
        if num in seen:
            notes.append(f"**CONFLICT with `{seen[num]}`**")
        seen[num] = name
        rows.append((name, num, ", ".join(notes) or "\u2014"))
    rows.sort(key=lambda r: int(r[1]))
    lines = [START, "| Define | Pin | Notes |", "|---|---|---|"]
    lines += [f"| `{n}` | GPIO {g} | {note} |" for n, g, note in rows]
    return "\n".join(lines)


def main():
    with open(CONFIG) as fh:
        source = fh.read()
    table = build_table(source)

    if "**CONFLICT" in table:
        print("WARNING: two defines share a GPIO. See the generated table.",
              file=sys.stderr)

    with open(DOC) as fh:
        doc = fh.read()
    start = doc.index(START)
    end = doc.index(END)
    doc = doc[:start] + table + "\n" + doc[end:]
    with open(DOC, "w") as fh:
        fh.write(doc)
    print(f"Regenerated the pin map in {DOC}")
    return 1 if "**CONFLICT" in table else 0


if __name__ == "__main__":
    sys.exit(main())
